import { readFileSync } from "node:fs";
import { existsSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { checkOklab, lin, oklab, srgbFromLinear, luma } from "@/lib/capypixel/colour";
import { bayer, bracketTable, ditherBias, floydSteinberg, lRange } from "@/lib/capypixel/dither";
import {
  assertPaletteMembership,
  disagreement,
  edgeSelectivity,
  flatness,
  hueFlipRate,
  toneSpread,
} from "@/lib/capypixel/metrics";
import { appendOutline, outline } from "@/lib/capypixel/outline";
import { FIXED_PALETTES, colourBins, kmeansPalette } from "@/lib/capypixel/palette";
import { labOf, levelsFn, saturate, tonalCurve, toneBands } from "@/lib/capypixel/prepass";
import { STYLE_ORDER, STYLE_PRESETS } from "@/lib/capypixel/presets";
import { exportSize, previewPitchFor, tightBboxFromAlpha } from "@/lib/capypixel/render";
import { largestPaletteShare, quantizeImage } from "@/lib/capypixel/quantize";
import type { QuantParams, RGB } from "@/lib/capypixel/types";
import { SUITE } from "@/lib/capytools/suite";
import { metadata } from "@/app/capypixel/page";

// ---------------------------------------------------------------------------
// Fixtures. The formulas are load-bearing: the golden index arrays below were
// generated by running the prototype's own core.js + cpu-naive.js (see the
// implementation plan, §9.4) over these exact cells, so changing a byte here
// changes which history the goldens pin.
// ---------------------------------------------------------------------------

/** Diagonal gradient with a hue cross-current. */
function gradientCells(cols: number, rows: number): Uint8Array {
  const n = cols * rows;
  const cells = new Uint8Array(n * 3);
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < cols; x++) {
      const i = y * cols + x;
      const t = x / (cols - 1);
      const u = y / (rows - 1);
      cells[i * 3] = Math.round(18 + 220 * t);
      cells[i * 3 + 1] = Math.round(24 + 180 * (1 - u));
      cells[i * 3 + 2] = Math.round(140 - 90 * t + 80 * u);
    }
  }
  return cells;
}

/**
 * A "portrait-ish" frame: dark navy backdrop, a lit gold drape in two folds, a
 * blue floor — flat regions with a few transitions, so flatness can tell 1-bit
 * art from a halftone screen.
 */
function portraitCells(cols: number, rows: number): Uint8Array {
  const n = cols * rows;
  const cells = new Uint8Array(n * 3);
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < cols; x++) {
      const i = y * cols + x;
      let r: number;
      let g: number;
      let b: number;
      if (y < rows * 0.3) {
        r = 16;
        g = 20;
        b = 34; // dark backdrop, below the black point
      } else if (y < rows * 0.48) {
        r = 190;
        g = 140;
        b = 60; // lit gold drape, bright enough to snap solid
      } else if (y < rows * 0.68) {
        r = 170;
        g = 125;
        b = 55; // drape, lower fold
      } else {
        r = 26;
        g = 36;
        b = 62; // blue floor, dark enough to go solid
      }
      cells[i * 3] = r;
      cells[i * 3 + 1] = g;
      cells[i * 3 + 2] = b;
    }
  }
  return cells;
}

function rampCells(cols: number, rows: number): Uint8Array {
  const n = cols * rows;
  const cells = new Uint8Array(n * 3);
  for (let i = 0; i < n; i++) {
    const v = Math.round((i / (n - 1)) * 255);
    cells[i * 3] = v;
    cells[i * 3 + 1] = v;
    cells[i * 3 + 2] = v;
  }
  return cells;
}

// ---------------------------------------------------------------------------
// §9.1 — the Oklab self-check
// ---------------------------------------------------------------------------

describe("Oklab self-check", () => {
  it("white → L 1, black → L 0, red lands on the published vector", () => {
    expect(checkOklab()).toBe(true);

    const w = oklab(255, 255, 255);
    expect(w[0]).toBeCloseTo(1, 6);
    expect(w[1]).toBeCloseTo(0, 6);
    expect(w[2]).toBeCloseTo(0, 6);

    const k = oklab(0, 0, 0);
    expect(k[0]).toBe(0);

    const r = oklab(255, 0, 0);
    expect(r[0]).toBeCloseTo(0.628, 3);
    expect(r[1]).toBeCloseTo(0.225, 3);
    expect(r[2]).toBeCloseTo(0.126, 3);
  });

  it("the transfer table round-trips through srgbFromLinear", () => {
    expect(lin(0)).toBe(0);
    expect(lin(255)).toBe(1);
    expect(lin(64)).toBeCloseTo(0.051269, 5);
    expect(lin(128)).toBeCloseTo(0.215861, 5);
    expect(lin(192)).toBeCloseTo(0.527115, 5);
    expect(srgbFromLinear(0)).toBe(0);
    expect(srgbFromLinear(1)).toBe(255);
    expect(srgbFromLinear(0.25)).toBeCloseTo(136.9602, 3);
    expect(srgbFromLinear(0.5)).toBeCloseTo(187.516, 3);
    // Fractional values (error diffusion) interpolate the table.
    expect(lin(127.5)).toBeGreaterThan(lin(127));
    expect(lin(127.5)).toBeLessThan(lin(128));
  });
});

// ---------------------------------------------------------------------------
// §9.4 — golden index arrays, generated from the prototype's own code
// ---------------------------------------------------------------------------

/** Runs one preset bundle over the given cells — the quantizeImage entry point. */
function run(cells: Uint8Array, cols: number, rows: number, p: QuantParams) {
  return quantizeImage(cells, cols, rows, p);
}

function presetParams(id: (typeof STYLE_ORDER)[number]): QuantParams {
  return { ...STYLE_PRESETS[id].params };
}

describe("golden index arrays — port drift guards", () => {
  it("faithful (derived median 16, Bayer 1/1) matches the prototype byte-for-byte", () => {
    const cells = gradientCells(8, 8);
    const got = run(cells, 8, 8, presetParams("faithful"));
    expect(Array.from(got.indices)).toEqual([
      5, 7, 7, 7, 13, 13, 15, 15, 5, 5, 5, 7, 13, 13, 15, 15, 4, 6, 6, 6, 12, 12, 14, 14, 4, 4,
      4, 6, 12, 12, 14, 14, 1, 1, 3, 3, 9, 9, 11, 11, 1, 1, 3, 3, 9, 9, 11, 11, 0, 0, 2, 2, 8,
      8, 10, 10, 0, 0, 2, 2, 8, 8, 10, 10,
    ]);
    expect(got.palette).toEqual([
      [33, 37, 207],
      [33, 87, 184],
      [96, 37, 181],
      [96, 87, 159],
      [33, 139, 161],
      [33, 191, 139],
      [96, 139, 136],
      [96, 191, 113],
      [159, 37, 156],
      [159, 87, 133],
      [222, 37, 130],
      [222, 87, 108],
      [159, 139, 110],
      [159, 191, 88],
      [222, 139, 84],
      [222, 191, 62],
    ]);
  });

  it("portrait (median 24, no dither, levels, bins 8, outline) matches the prototype", () => {
    const cells = gradientCells(8, 8);
    const got = run(cells, 8, 8, presetParams("portrait"));
    expect(Array.from(got.indices)).toEqual([
      15, 15, 16, 23, 23, 23, 23, 23, 14, 15, 16, 16, 20, 22, 23, 23, 10, 10, 24, 14, 20, 20,
      22, 22, 11, 24, 13, 24, 18, 24, 21, 21, 8, 24, 12, 12, 12, 18, 19, 19, 5, 6, 6, 9, 12,
      17, 17, 19, 1, 3, 5, 7, 9, 17, 17, 17, 24, 24, 1, 2, 4, 4, 17, 17,
    ]);
    // 24 derived entries plus the appended outline colour.
    expect(got.palette).toHaveLength(25);
    expect(got.palette[24]).toEqual([5, 5, 5]);
  });

  it("whale (fixed 7-blue ramp, levels, sat 0.25) matches the prototype", () => {
    const cells = gradientCells(8, 8);
    const got = run(cells, 8, 8, presetParams("whale"));
    expect(Array.from(got.indices)).toEqual([
      6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 6,
      6, 6, 2, 4, 4, 5, 4, 5, 5, 6, 2, 2, 3, 3, 4, 4, 5, 5, 0, 1, 1, 2, 2, 2, 2, 4, 0, 0, 0, 0,
      1, 1, 2, 2,
    ]);
    expect(got.palette).toEqual(FIXED_PALETTES.whale);
  });

  it("game boy (fixed 4-green, band 0.5, curve 0.2/0.8) matches the prototype", () => {
    const cells = gradientCells(8, 8);
    const got = run(cells, 8, 8, presetParams("gameboy"));
    expect(Array.from(got.indices)).toEqual([
      3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 3, 3, 3, 3, 2, 1, 2, 2, 2, 2,
      2, 3, 1, 1, 1, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
      0, 0, 0, 0,
    ]);
    expect(got.palette).toEqual([
      [15, 56, 15],
      [48, 98, 48],
      [139, 172, 15],
      [155, 188, 15],
    ]);
  });

  it("1-bit (band 0.35, curve 0.26/0.74) matches the prototype, dither and all", () => {
    const cells = portraitCells(24, 24);
    const got = run(cells, 24, 24, presetParams("1bit"));
    // Solid runs with the dithered transitions between them — the curve snaps
    // the backdrop, both drape folds and the floor solid, and only the rows
    // where tones change dither. (Run lengths verified against the prototype.)
    const expected = ("0".repeat(192) + "1".repeat(216) + "0".repeat(168))
      .split("")
      .map(Number);
    expect(Array.from(got.indices)).toEqual(expected);
    expect(got.palette).toEqual([
      [0, 0, 0],
      [255, 255, 255],
    ]);
  });

  it("1-bit halftone (band 1, levels on, grid 700 look) matches the prototype", () => {
    const cells = portraitCells(24, 24);
    const got = run(cells, 24, 24, presetParams("1bit-halftone"));
    // The verified prototype output, one fixture row per line: solid 1s where
    // the stretched drape lands, and the Bayer screen (every fourth cell
    // flipped) where the black floor crosses the bracket.
    expect(Array.from(got.indices)).toEqual([
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,
    ]);
  });
});

// ---------------------------------------------------------------------------
// §9.2 — determinism is a test, not a hope
// ---------------------------------------------------------------------------

describe("determinism — same input, byte-identical indices, per preset", () => {
  for (const id of STYLE_ORDER) {
    it(`${id} quantizes identically twice`, () => {
      const usePortrait = id === "1bit" || id === "1bit-halftone";
      const cells = usePortrait ? portraitCells(24, 24) : gradientCells(8, 8);
      const dim = usePortrait ? 24 : 8;
      const p = presetParams(id);
      const a = run(cells, dim, dim, p);
      const b = run(cells, dim, dim, p);
      expect(disagreement(a.indices, b.indices)).toBe(0);
      expect(Array.from(a.indices)).toEqual(Array.from(b.indices));
    });
  }

  it("floyd and none modes are deterministic too", () => {
    const cells = gradientCells(16, 16);
    for (const dither of ["floyd", "none"] as const) {
      const p = { ...presetParams("faithful"), dither };
      const a = run(cells, 16, 16, p);
      const b = run(cells, 16, 16, p);
      expect(disagreement(a.indices, b.indices)).toBe(0);
    }
  });
});

// ---------------------------------------------------------------------------
// §9.3 — palette invariants
// ---------------------------------------------------------------------------

describe("palette invariants", () => {
  for (const id of STYLE_ORDER) {
    it(`${id}: every index in range, no duplicate entries`, () => {
      const usePortrait = id === "1bit" || id === "1bit-halftone";
      const cells = usePortrait ? portraitCells(24, 24) : gradientCells(8, 8);
      const dim = usePortrait ? 24 : 8;
      const got = run(cells, dim, dim, presetParams(id));
      expect(assertPaletteMembership(got.indices, got.palette)).toBe(0);
      const seen = new Set(got.palette.map((c) => c.join(",")));
      expect(seen.size).toBe(got.palette.length);
    });
  }

  it("the outline appends exactly one entry, 30% below the darkest in linear light", () => {
    const palette: RGB[] = [
      [10, 20, 30],
      [40, 50, 60],
      [70, 80, 90],
      [100, 110, 120],
    ];
    const o = appendOutline(palette);
    expect(o.palette).toHaveLength(5);
    expect(o.index).toBe(4);
    expect(o.colour).toEqual([3, 7, 13]);
    expect(palette).toHaveLength(4); // the input palette is untouched
  });

  it("k-means beats median-cut on Oklab error (the measured reason it ships)", () => {
    const cells = gradientCells(16, 16);
    const idxKm = run(cells, 16, 16, { ...presetParams("faithful"), palette: "kmeans" });
    const idxMc = run(cells, 16, 16, presetParams("faithful"));
    // Both errors are measured by the same metric on the same prepared grid,
    // so the comparison is apples to apples. (The prototype's headline number
    // is 1.9× lower at 16 colours; on this small fixture a strict win is the
    // honest claim.)
    expect(idxKm.metrics.oklabError).toBeLessThan(idxMc.metrics.oklabError);
  });
});

// ---------------------------------------------------------------------------
// §9.5 — the flatness regression guard
// ---------------------------------------------------------------------------

describe("1-bit flatness — the guard against reintroducing the halftone bug", () => {
  it("the portrait fixture through the 1bit preset scores flatness ≥ 0.8", () => {
    const cells = portraitCells(24, 24);
    const got = run(cells, 24, 24, presetParams("1bit"));
    expect(got.metrics.flatness).toBeGreaterThanOrEqual(0.8);
  });

  it("the contrast-modulated bias snaps decisive tones solid and dithers only mid-bracket", () => {
    const plab = FIXED_PALETTES["1bit"].map((p) => oklab(p[0], p[1], p[2])) as Array<[number, number, number]>;
    const br = bracketTable(plab);
    // Near an entry: zero bias — the cell snaps solid.
    expect(ditherBias(0.05, br, 0, 0, 1, 0.35)).toBe(0);
    // Mid-bracket: the Bayer bias, scaled to the bracket.
    const mid = ditherBias(0.5, br, 0, 0, 1, 0.35);
    expect(Math.abs(mid)).toBeGreaterThan(0);
    // Band 0 disables dithering; band 1 keeps dithering tones that band 0.35
    // has already released to solid (the snap at L 0.8).
    expect(ditherBias(0.5, br, 0, 0, 1, 0)).toBe(0);
    expect(ditherBias(0.8, br, 0, 0, 1, 0.35)).toBe(0);
    expect(Math.abs(ditherBias(0.8, br, 0, 0, 1, 1))).toBeGreaterThan(0);
    // The bias lives in the palette's own luminance spacing.
    expect(lRange(plab as Array<[number, number, number]>)).toBeCloseTo(1, 6);
    expect(bayer(0, 0)).toBeCloseTo(-0.5 + 0, 12);
  });
});

// ---------------------------------------------------------------------------
// §9.6 — pre-pass maths, unit goldens from the prototype
// ---------------------------------------------------------------------------

describe("pre-pass maths", () => {
  it("levels: a 2%/98% percentile stretch on a full ramp barely moves it", () => {
    const cells = rampCells(8, 8);
    const fn = levelsFn(cells, 64, 0.02, 0.98);
    for (const [input, expected] of [
      [0, 0],
      [64, 62],
      [128, 128],
      [192, 194],
      [255, 255],
    ] as const) {
      const got = fn(input, input, input);
      expect(got.map(Math.round)).toEqual([expected, expected, expected]);
    }
  });

  it("tonalCurve: the 1-bit black/white points collapse mid-tones toward the extremes", () => {
    const cells = Uint8Array.from([0, 0, 0, 64, 64, 64, 128, 128, 128, 255, 255, 255]);
    const got = tonalCurve(cells, 4, 0.26, 0.74, 1);
    expect(Array.from(got)).toEqual([
      0, 0, 0, 29, 29, 29, 160, 160, 160, 255, 255, 255,
    ]);
  });

  it("tonalCurve: gamma bends the middle (1.5 brightens a mid-grey)", () => {
    const cells = Uint8Array.from([128, 128, 128, 128, 128, 128]);
    expect(Array.from(tonalCurve(cells, 2, 0, 1, 1.5))).toEqual([161, 161, 161, 161, 161, 161]);
  });

  it("saturate: 0 is greyscale by luma, 1 is identity, 0.25 on white is white", () => {
    expect(saturate(200, 100, 50, 0).map(Math.round)).toEqual([118, 118, 118]);
    expect(saturate(200, 100, 50, 0.5).map(Math.round)).toEqual([159, 109, 84]);
    // 0.25 is not exact in binary float; the pipeline clamps into a Uint8Array,
    // which is the rounding that matters.
    expect(saturate(255, 255, 255, 0.25).map(Math.round)).toEqual([255, 255, 255]);
    expect(luma(200, 100, 50)).toBeCloseTo(117.65, 2);
  });

  it("colourBins snaps to the lattice centres (derivation input only)", () => {
    const cells = Uint8Array.from([0, 0, 0, 64, 0, 0, 128, 0, 0, 192, 0, 0, 255, 0, 0]);
    expect(Array.from(colourBins(cells, 5, 8))).toEqual([
      16, 16, 16, 80, 16, 16, 144, 16, 16, 208, 16, 16, 240, 16, 16,
    ]);
  });

  it("toneBands: quantise L into bands, rebuilt in linear light", () => {
    const cells = Uint8Array.from([0, 0, 0, 128, 128, 128, 255, 255, 255]);
    expect(Array.from(toneBands(cells, 3, 4))).toEqual([0, 0, 0, 135, 135, 135, 213, 213, 213]);
  });

  it("bins affect derivation only — the source cells are never mutated", () => {
    const cells = gradientCells(16, 16);
    const before = Uint8Array.from(cells);
    const p = { ...presetParams("faithful"), bins: 8 };
    run(cells, 16, 16, p);
    expect(Array.from(cells)).toEqual(Array.from(before));
    // ...and binning genuinely changes what the palette is derived from.
    const binned = run(cells, 16, 16, p);
    const plain = run(cells, 16, 16, { ...presetParams("faithful") });
    expect(Array.from(binned.palette)).not.toEqual(Array.from(plain.palette));
  });

  it("k-means palette matches the prototype's clustering on bare lab data", () => {
    const cells = gradientCells(8, 8);
    const got = kmeansPalette(cells, labOf(cells, 64), 64, 16, 6);
    expect(got).toEqual([
      [43, 34, 205],
      [112, 37, 176],
      [68, 70, 179],
      [49, 114, 167],
      [156, 45, 154],
      [152, 95, 134],
      [217, 33, 135],
      [223, 75, 114],
      [55, 161, 144],
      [144, 127, 123],
      [228, 118, 92],
      [175, 153, 99],
      [128, 178, 107],
      [81, 204, 114],
      [228, 170, 69],
      [207, 204, 63],
    ]);
  });
});

// ---------------------------------------------------------------------------
// Outline pass + metrics
// ---------------------------------------------------------------------------

describe("outline pass and metrics", () => {
  it("outline marks the strongest gradient cells and rewrites them to the outline entry", () => {
    const cells = gradientCells(8, 8);
    const indices = Uint8Array.from({ length: 64 }, (_, i) => i % 4);
    const palette: RGB[] = [
      [10, 20, 30],
      [40, 50, 60],
      [70, 80, 90],
      [100, 110, 120],
    ];
    const o = appendOutline(palette);
    const marked = outline(cells, indices, 8, 8, { index: o.index, threshold: 0.07, thickness: 1 });
    const markedCount = Array.from(marked).filter((v) => v === 4).length;
    expect(markedCount).toBe(5);
    expect(marked).toBeInstanceOf(Int32Array);
  });

  it("flatness reads solid vs screen; hueFlipRate sees what mse cannot", () => {
    // Two solid bands: horizontal pairs all match, only the band boundary dithers.
    const indices = Uint8Array.from([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]);
    expect(flatness(indices, 4, 4)).toBeGreaterThan(0.5);
    const screen = Uint8Array.from([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0]);
    expect(flatness(screen, 4, 4)).toBe(0);
    const cells = Uint8Array.from([255, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 255]);
    const palette: RGB[] = [
      [0, 0, 255],
      [255, 255, 0],
    ];
    // The warm cell maps to the cool entry and flips; the two cool cells map to
    // the same cool entry and don't; the black cell is near-neutral, skipped.
    expect(hueFlipRate(cells, Uint8Array.from([0, 0, 0, 0]), palette, 4)).toBeCloseTo(1 / 3, 9);
  });

  it("the rest of the metric set runs and stays in [0, ∞)", () => {
    const cells = gradientCells(8, 8);
    const got = run(cells, 8, 8, presetParams("faithful"));
    expect(got.metrics.hueFlipRate).toBeGreaterThanOrEqual(0);
    expect(got.metrics.oklabError).toBeGreaterThan(0);
    expect(largestPaletteShare(got.indices, got.palette.length)).toBeGreaterThan(0);
    expect(toneSpread(cells, 64)).toBeGreaterThan(0.5);
    expect(edgeSelectivity(cells, got.indices, got.palette, 8, 8)).toBeGreaterThan(0);
  });

  it("floyd–steinberg keeps every index in range and diffuses", () => {
    const cells = gradientCells(8, 8);
    const out = floydSteinberg(cells, FIXED_PALETTES.whale, 8, 8, 1);
    expect(assertPaletteMembership(Uint8Array.from(out), FIXED_PALETTES.whale)).toBe(0);
    expect(out.length).toBe(64);
  });
});

// ---------------------------------------------------------------------------
// §9.7 — preset integrity: every bundle matches the plan's measured table
// ---------------------------------------------------------------------------

describe("preset integrity — the measured bundles, exactly", () => {
  const expected: Record<string, Partial<QuantParams>> = {
    faithful: { palette: "median", colors: 16, dither: "bayer", amount: 1, band: 1, gutter: 0, levels: false, bands: 0, bins: 0, outline: false, black: 0, white: 1, gamma: 1, grid: 150 },
    portrait: { palette: "median", colors: 24, dither: "none", amount: 0, gutter: 0, levels: true, bands: 0, bins: 8, outline: true, black: 0, white: 1, gamma: 1, grid: 150 },
    whale: { palette: "fixed", fixedPalette: "whale", dither: "bayer", amount: 1, band: 1, gutter: 1, levels: true, saturation: 0.25, bands: 0, bins: 0, outline: false, black: 0, white: 1, gamma: 1, grid: 120 },
    gameboy: { palette: "fixed", fixedPalette: "gameboy", dither: "bayer", amount: 1, band: 0.5, gutter: 0, levels: false, saturation: 0, bands: 0, bins: 0, outline: false, black: 0.2, white: 0.8, gamma: 1, grid: 110 },
    "1bit": { palette: "fixed", fixedPalette: "1bit", dither: "bayer", amount: 1, band: 0.35, gutter: 0, levels: false, saturation: 0, bands: 0, bins: 0, outline: false, black: 0.26, white: 0.74, gamma: 1, grid: 70 },
    "1bit-halftone": { palette: "fixed", fixedPalette: "1bit", dither: "bayer", amount: 1, band: 1, gutter: 0, levels: true, saturation: 0, bands: 0, bins: 0, outline: false, black: 0, white: 1, gamma: 1, grid: 700 },
  };

  it("each preset carries the exact §3.2 bundle", () => {
    for (const id of STYLE_ORDER) {
      const p = STYLE_PRESETS[id].params;
      for (const [key, value] of Object.entries(expected[id])) {
        expect(p[key as keyof QuantParams]).toBe(value as number | boolean | string);
      }
    }
  });

  it("every preset is complete: all QuantParams fields present and typed", () => {
    const shape: QuantParams = { ...STYLE_PRESETS.faithful.params };
    for (const id of STYLE_ORDER) {
      const p = STYLE_PRESETS[id].params;
      for (const key of Object.keys(shape) as Array<keyof QuantParams>) {
        expect(p[key], `${id}.${key}`).toBeDefined();
      }
      expect(p.outlineThreshold).toBe(0.07);
      expect(p.outlineThickness).toBe(1);
      expect(p.cell).toBe(4);
    }
  });

  it("the halftone stays labelled as what it is", () => {
    expect(STYLE_PRESETS["1bit-halftone"].blurb).toMatch(/halftone/i);
    expect(STYLE_PRESETS.whale.blurb).toMatch(/not a filter/);
  });
});

// ---------------------------------------------------------------------------
// §9 (browser-only paths) — the pure decision helpers
// ---------------------------------------------------------------------------

describe("render decision helpers", () => {
  it("tightBboxFromAlpha finds the ink extents on a synthetic alpha scan", () => {
    // 8×8 RGBA, ink (alpha 255) at rows 2–3, cols 3–5; one faint pixel (alpha 10)
    // that sits below the threshold.
    const w = 8;
    const h = 8;
    const data = new Uint8ClampedArray(w * h * 4);
    for (let y = 2; y <= 3; y++) {
      for (let x = 3; x <= 5; x++) {
        data[(y * w + x) * 4 + 3] = 255;
      }
    }
    data[(6 * w + 1) * 4 + 3] = 10;
    expect(tightBboxFromAlpha(data, w, h, 24)).toEqual({ x0: 3, y0: 2, x1: 5, y1: 3 });
    expect(tightBboxFromAlpha(new Uint8ClampedArray(w * h * 4), w, h, 24)).toBeNull();
  });

  it("export size is exact cells × cell × integer scale", () => {
    expect(exportSize(150, 100, 4, 1)).toEqual({ width: 600, height: 400 });
    expect(exportSize(150, 100, 4, 8)).toEqual({ width: 4800, height: 3200 });
  });

  it("the preview pitch keeps the tile look at a smaller price", () => {
    // Small grid: 4px preview cells, gutter scaled 1/4 → 1.
    expect(previewPitchFor(120, 4, 1)).toEqual({ cell: 4, gutter: 1 });
    // Big grid: 2px preview cells.
    expect(previewPitchFor(700, 4, 1).cell).toBe(2);
    // Photos (gutter 0) stay gapless at any pitch.
    expect(previewPitchFor(600, 4, 0)).toEqual({ cell: 2, gutter: 0 });
  });
});

// ---------------------------------------------------------------------------
// §9.8 — registration parity
// ---------------------------------------------------------------------------

describe("CapyPixel registration", () => {
  it("sits tenth in the SUITE with its plate", () => {
    expect(SUITE).toHaveLength(11);
    const row = SUITE[9];
    expect(row.name).toBe("CapyPixel");
    expect(row.href).toBe("/capypixel");
    expect(row.cat).toBe("browser");
    expect(row.plate).toEqual({ src: "/plates/lab-10.webp", width: 896, height: 1200 });
  });

  it("has a page exporting the metadata the suite expects", () => {
    expect(metadata.title).toContain("CapyPixel");
    expect(metadata.description).toContain("100% in your browser");
  });

  it("ships its lab plate", () => {
    expect(existsSync(join(process.cwd(), "public", "plates", "lab-10.webp"))).toBe(true);
  });

  it("the README carries the tool's section and the count", () => {
    const readme = readFileSync(join(process.cwd(), "README.md"), "utf8");
    expect(readme).toContain("## 10. CapyPixel");
    expect(readme).toContain("Eleven so far");
  });
});
