import { Metadata } from 'next';
import { LegalP, LegalPage, LegalSection, LegalUL } from '@/components/legal/LegalPage';

export const metadata: Metadata = {
  title: 'Terms of Service | CapyResume',
  description:
    'Terms for using CapyResume, a free and open-source résumé builder that runs entirely in your browser.',
};

export default function TermsOfServicePage() {
  return (
    <LegalPage
      title="Terms of service"
      lead="Plain terms for a small, free tool. CapyResume runs in your browser, keeps your résumé there, and charges nothing. These terms are short because there is very little for them to govern."
    >
      <LegalSection heading="1. Acceptance">
        <LegalP>
          By using CapyResume you agree to these terms. If you do not agree with them, please do not
          use the tool — it is free, so there is nothing lost by walking away.
        </LegalP>
      </LegalSection>

      <LegalSection heading="2. What CapyResume is">
        <LegalP>
          CapyResume is a client-side résumé and CV builder. You fill in a structured editor, and it
          produces a PDF with real selectable text, a Word (.docx) file, and a JSON copy of your own
          data. Everything — the editing, the rendering and the file generation — happens inside
          your browser.
        </LegalP>
        <LegalUL>
          <li>No account is required to use it, and none is offered.</li>
          <li>Nothing you type is uploaded to us.</li>
          <li>Your work is saved in your own browser, not on a server.</li>
        </LegalUL>
      </LegalSection>

      <LegalSection heading="3. The free tier, and what we commit to">
        <LegalP>
          The free tier is the whole editor: every section type, the available templates, and
          unlimited PDF, DOCX and JSON exports. There is no watermark and there is no export limit.
        </LegalP>
        <LegalP>
          We state this as a commitment rather than a perk:{' '}
          <strong className="text-foreground">
            we will not put a watermark on your résumé, and we will not lock the export of your own
            document behind a payment.
          </strong>{' '}
          It is your document. If we ever add paid features they will be additions, not a toll on
          getting your résumé out.
        </LegalP>
      </LegalSection>

      <LegalSection heading="4. Optional AI features (bring your own key)">
        <LegalP>
          The tool can offer optional help with wording and formatting, using an API key you supply
          from a provider you choose. Requests go directly from your browser to that provider; we
          are not in the request path and never see your key or your text.
        </LegalP>
        <LegalP>By using this feature you accept that:</LegalP>
        <LegalUL>
          <li>
            <strong className="text-foreground">The key is yours.</strong> You are responsible for
            obtaining it, keeping it valid, and for any charges your provider bills you.
          </li>
          <li>
            The provider&apos;s own terms of service apply to your use of their API, in addition to
            these terms. You must comply with them.
          </li>
          <li>
            <strong className="text-foreground">You must review anything the AI produces.</strong>{' '}
            Language models can be confidently wrong, can invent details, and can overstate what you
            actually did. That risk is yours, and it lands on the document you send to employers.
          </li>
          <li>
            We provide no warranty about the accuracy, tone or suitability of AI-generated text, and
            we are not liable for content you chose to keep.
          </li>
        </LegalUL>
        <LegalP>
          Nothing generated by these features is legal, career or professional advice.
        </LegalP>
      </LegalSection>

      <LegalSection heading="5. Your content">
        <LegalP>
          You own everything you write in CapyResume, entirely and without qualification. We claim
          no licence over it — we could not, since we never receive it. You are free to use the
          exported files for any purpose.
        </LegalP>
        <LegalP>
          You are responsible for the accuracy of what you put in your résumé, and for how you use
          it when applying for a role.
        </LegalP>
      </LegalSection>

      <LegalSection heading="6. Fair use">
        <LegalP>
          Please do not use CapyResume to create fraudulent or deliberately misleading documents, or
          to impersonate another person. This is a tool for describing your own experience; misusing
          it in an application is likely to be a matter for the employer and possibly the law, and
          it is not something we can help with.
        </LegalP>
      </LegalSection>

      <LegalSection heading="7. No guarantee of outcomes">
        <LegalP>
          CapyResume produces a plain, single-column, text-based document — the layout that
          applicant-tracking systems handle best, and DOCX is generally the safest format to submit.
          But we cannot promise any particular result, and we do not claim otherwise:
        </LegalP>
        <LegalUL>
          <li>
            We do not guarantee that any employer or recruiter&apos;s system will parse your file
            correctly. Parsers vary, and layout is only one of many inputs.
          </li>
          <li>We do not guarantee interviews, offers or any other outcome.</li>
          <li>We do not guarantee that the tool will be uninterrupted or free of bugs.</li>
        </LegalUL>
      </LegalSection>

      <LegalSection heading="8. Keep your own backup">
        <LegalP>
          Your résumé is stored in your browser, which means it is yours to look after. Clearing
          your browsing data, using incognito mode, uninstalling the browser or switching devices
          will remove or hide it, and we cannot restore it because we never had a copy.
        </LegalP>
        <LegalP>
          Use the JSON export as a backup. We are not liable for lost work that could have been
          exported.
        </LegalP>
      </LegalSection>

      <LegalSection heading="9. Open source and licensing">
        <LegalP>
          The CapyResume source code is released under the Apache-2.0 licence, and the full history
          of these pages is public in the same repository. That licence covers the code. Your use of
          the hosted copy of the tool is governed by these terms, and nothing here restricts the
          rights that licence grants you over the code itself.
        </LegalP>
      </LegalSection>

      <LegalSection heading="10. Paid features">
        <LegalP>
          There are none today, and everything described in section 3 is free. If we introduce a
          paid tier — for example extra template packs, a cover-letter bundle or bulk tailoring — it
          will be optional, it will require creating an account, and these terms will be updated
          before it launches to describe what that involves.
        </LegalP>
      </LegalSection>

      <LegalSection heading="11. Disclaimer of warranties">
        <LegalP>
          CapyResume is provided &quot;as is&quot; and &quot;as available&quot;, without warranties
          of any kind, express or implied, including any implied warranty of merchantability,
          fitness for a particular purpose or non-infringement. You use it at your own risk.
        </LegalP>
      </LegalSection>

      <LegalSection heading="12. Limitation of liability">
        <LegalP>
          To the maximum extent permitted by law, CapyResume and its contributors are not liable for
          any indirect, incidental, special, consequential or punitive damages, or for any lost
          profits, lost data or lost opportunities, arising from your use of — or inability to use —
          the tool. This includes lost résumé content and unsuccessful job applications.
        </LegalP>
        <LegalP>
          Because the tool is provided free of charge, our total aggregate liability to you is
          limited to the amount you have paid us, which is nothing.
        </LegalP>
      </LegalSection>

      <LegalSection heading="13. Changes to these terms">
        <LegalP>
          We may update these terms as the tool changes. The &quot;last updated&quot; date at the
          top of this page will change with them, and the previous versions remain visible in the
          repository history. Continuing to use CapyResume after a change means you accept the
          updated terms.
        </LegalP>
      </LegalSection>

      <LegalSection heading="14. Contact">
        <LegalP>
          This is a small open-source project, so the issue tracker is the right place for
          questions, corrections and bug reports.
        </LegalP>
      </LegalSection>
    </LegalPage>
  );
}
